name: ijapesigan-r2u

on:
  workflow_run:
    workflows: [ "ijapesigan-rarch" ]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: jeksterslab/dynr-rocker
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      packages: read
      statuses: write

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Run
        run: |
          Rscript -e "source('script.R'); foo('ijapesigan-r2u')"
      - 
        name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Automated build."
